ALTER PROCEDURE [dbo].[SP_DEL_FUTBOLISTA]
     @PI_ID_JUGADOR INTEGER

AS
BEGIN
       UPDATE Futbolista
    SET Activo = '0'
    WHERE Id_jugador = @PI_ID_JUGADOR;
END
GO
ALTER PROCEDURE [dbo].[SP_INS_FUTBOLISTA]
    @PI_ID_JUGADOR INTEGER,
    @PV_NOMBRE VARCHAR(50),
    @PV_ACTIVO VARCHAR(1),
    @PD_FECHAINICIO DATETIME

AS
     DECLARE @CONTADOR_ID INTEGER;

BEGIN
	SELECT  @CONTADOR_ID=ISNULL(MAX(ID_JUGADOR),0)+1
	FROM FUTBOLISTA;

	INSERT INTO FUTBOLISTA(ID_JUGADOR,NOMBRE,ACTIVO,FECHAINICIO)
	VALUES(@CONTADOR_ID,@PV_NOMBRE,'A',GETDATE());
END
GO
ALTER PROCEDURE [dbo].[SP_UPD_FUTBOLISTA]
	@PI_ID_JUGADOR INTEGER,
    @PV_NOMBRE VARCHAR(50),
    @PV_ACTIVO VARCHAR(1),
    @PD_FECHAINICIO DATETIME,
    @PD_FECHA_FINAL DATETIME,
    @PD_FECHA_MODIFICACION DATETIME,
    @PD_FUTBOLISTA_MODIFICACION DATETIME

AS
BEGIN
    UPDATE Futbolista
    SET Nombre = @PV_NOMBRE,
        Activo = @PV_ACTIVO,
        FechaInicio = @PD_FECHAINICIO,
        FechaFinal = @PD_FECHA_FINAL,
        FechaModificacion = @PD_FECHA_MODIFICACION,
        futbolistaModificacion = @PD_FUTBOLISTA_MODIFICACION
    WHERE Id_jugador = @PI_ID_JUGADOR;
END
GO
ALTER PROCEDURE [dbo].[SP_GET_FUTBOLISTA]
     @PI_ID_JUGADOR INTEGER

AS
BEGIN
    SELECT * FROM Futbolista WHERE Id_jugador = @PI_ID_JUGADOR;
END
GO
ALTER PROCEDURE [dbo].[SP_GET_FUTBOLISTAs]


AS
BEGIN
    SELECT * FROM Futbolista WHERE Activo = 'A';
END
GO
ALTER PROCEDURE [dbo].[SP_GET_Historial]
     @PI_ID_JUGADOR INTEGER

AS
BEGIN
   SELECT e.Nombre AS NombreEquipo, f.Nombre AS NOMBREJUGADOR, he.FechaInicio , he.FechaFinal
    FROM HistoricoEquipos he
    JOIN Equipos e ON he.EquipoId = e.Id_equipo
	JOIN Futbolista f ON he.FutbolistaId = f.Id_jugador
    WHERE he.FutbolistaId = @PI_ID_JUGADOR;
END